### ISSUE TITLE
"DeviceioControl() failed, error is 1" has occured.

### ISSUE THREAD

**Issue by a3coo3a** [LINBIT/windrbd#18] opened 2021-09-17 00:58 UTC
This error occurred while testing WinDRBD. ( with Window Server 2019 )

Disconnect the SecondaryNode and put data into the PrimaryNode to create ```out-of-sync``` data.

Both servers were ```drbdadm down foo```

first Node1
```
drbdadm up foo
drbdadm disconnect foo
drbdadm primary foo --force
drbdadm connect foo
```

Second Node2
```
drbdadm up foo
drbdadm disconnect foo
drbdadm connect --discard-my-data foo
```

And through ```drbdsetup events2 foo``` confirmed that there was a split brain.

tried to change it back to normal

I checked the status(```drbdadm status foo```) after ```drbdadm down foo → drbdadm up foo``` the SecondaryNode side.

I got the following error:
```
DeviceIoControl() failed, error 1
foo : error sending config command
```

=======================================================
Another thing is the situation.

This simply happens under normal conditions.

```drbdadm cstate foo```
```
UpToData/UpToData
```
At this time, it occurs when one node goes ```drabdadm down foo``` and then goes ```drbdsetup status foo --v --s```or```drbdadm up foo``` almost immediately.

error msg
```
> drbdsetup status foo --v --s
DeviceIoControl() failed, error is 1
all : error sending config command 
# No currently configured DRBD found.
foo : No such resource
```
Is there a standard that requires a certain amount of time to elapse after being down?

Both of the above situations produced the same error.

Even after this error appears, the server itself is shutdown, so we take it seriously.

**Comment by johannesthoma** [comment] 2021-09-22 14:16
Hi InYoung,

Thank you for your bug report. I will try to reproduce the issue and fix it in the next days. Maybe meanwhile you could post the DRBD configs of both nodes?

Best regards,

- Johannes

**Comment by a3coo3a** [comment] 2021-09-23 05:06
Hi Johannes,

Fortunately, the test server restarted normally after rebooting or reconnecting after a certain period of time has elapsed. ( I don't know exactly how much time has passed )

I hope the above bug helps improve WinDRBD.

**Comment by johannesthoma** [comment] 2021-09-23 11:12
Hi InYoung,

Does the server blue screen? That should not happen ... which WinDRBD
version are you using? Could you maybe tell me the blue screen code?

To grab the blue screen you need to disable automatic restart after
blue screen here's a howto:
--
Press the Win + R keys to open Run, type SystemPropertiesAdvanced.exe into Run, and click/tap on OK to open advanced System Properties.

Click/tap on the Settings button under Startup and Recovery

Check (enable - default) or uncheck (disable) the Automatically restart box under System failure for what you want, and click/tap on OK.
--
Also please send me your drbd.conf.

Thanks a lot yes the bug helps to improve WinDRBD,

Best regards,

- Johannes

**Comment by johannesthoma** [comment] 2021-09-23 13:41
Hi InYoung,

I tried to reproduce the issue but failed to do so. Everything you wrote works for me.
Maybe you could explain more detailed what you have done. And please send me the
drbd.conf.

Which WinDRBD version are you using?

Thanks a lot and Best regards,

- Johannes

**Comment by johannesthoma** [comment] 2021-10-05 16:03
Hello,

Is this still an issue and can I help? If not please close this issue,

Thanks a lot and best regards,

- Johannes

**Closed** 2022-02-08 13:48 UTC
